---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: domains.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: Domain
    plural: domains
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        domain:
          type: string
        kind:
          type: string
        metadata:
          type: object
        nameServer:
          type: string
      required:
      - domain
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
