---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: servicednsrecords.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: ServiceDNSRecord
    plural: servicednsrecords
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            allowServiceWithoutEndpoints:
              type: boolean
            dnsPrefix:
              type: string
            domainRef:
              type: string
            externalName:
              type: string
            recordTTL:
              format: int64
              type: integer
          required:
          - domainRef
          type: object
        status:
          properties:
            dns:
              items:
                properties:
                  cluster:
                    type: string
                  loadBalancer:
                    type: object
                  region:
                    type: string
                  zone:
                    type: string
                type: object
              type: array
            domain:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
