---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedservicestatuses.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedServiceStatus
    plural: federatedservicestatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        clusterStatus:
          items:
            properties:
              clusterName:
                type: string
              status:
                type: object
            type: object
          type: array
        kind:
          type: string
        metadata:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
